- hosts: all
  roles:
    - ansible-role-adduser
    - ansible-cronjob
  vars:
    adduser__users:
      - name: "steeve"
        ssh_key: ["ssh-rsa blahblahblah"]
        shell: "/bin/bash"
        home: "/home/steeve"
        system: true

    cronjobs:
      - name: "Example cronjob"
        user: "root"
        state: "present"
        minute: "20"
        hour: "*"
        day: "*"
        weekday: "*"
        month: "*"
        job: "curl www.google.com"
