---
- name: Install and start the service
  hosts: all
  become: true
  tasks:
  - name: installing nginx
    apt:
     name: nginx
     state: present
  - name: copy index.html
    template:
         src: /home/yasir/ansibletask/playbooks/index.html
         dest: /var/www/html/index.html

  - name: starting nginx
    service:
     name: nginx
     state: started
     enabled: true
