name: Deploy EC2 with Terraform Module

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init
        working-directory: ~/actions-runner/_work/mygitactions/mygitactions

      - name: Plan Terraform
        run: terraform plan
        working-directory: ~/actions-runner/_work/mygitactions/mygitactions

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ~/actions-runner/_work/mygitactions/mygitactions

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
