name: Echo Hostname on self hosted runner

on:
  push:
    branches:
      - main

jobs:
  echo-hostname:
    runs-on: self-hosted

    steps:
      - name: cloning the repo
        uses: actions/checkout@v4
              #- name: cloning repo
        #run: git clone https://github.com/yasirdev111/mygitactions.git
      - name: Echo Hostname
        run: hostname
      - name: current dir
        run: pwd
      - name: changine directory
        run: |
          cd /home/yasir/actions-runner/_work/mygitactions/mygitactions
          pwd
          ls -l
          echo "running hostname.sh file"
          chmod +x hostname.sh
          ./hostname.sh
      - name: Login to macAir
        run: |
          ssh yasir@10.0.0.101
          touch filethroughgitaction
          hostname
