name: Echo Hostname

on:
  push:
    branches:
      - main

jobs:
  echo-hostname:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo Hostname
        run: hostname
