name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Required Roles
        run: |
          mkdir -p roles
          cd roles
          git clone https://github.com/Grokon/ansible-role-adduser.git ansible-role-adduser
          git clone https://github.com/bytepark/ansible-cronjob.git ansible-cronjob

      - name: Run Ansible Playbook
        run: |
          ansible-playbook add-user.yml -i inventory
        working-directory: ${{ github.workspace }}

