name: Echo Hostname on self hosted runner

on:
  push:
    branches:
      - main

jobs:
  echo-hostname:
    runs-on: self-hosted

    steps:
      - name: cloning the repo
        uses: actions/checkout@v4
              #- name: cloning repo
        #run: git clone https://github.com/yasirdev111/mygitactions.git
      - name: Echo Hostname
        run: hostname
      - name: current dir
        run: pwd
      - name: changine directory
        run: |
          Navigate to the working directory
          cd /home/yasir/actions-runner/_work/mygitactions/mygitactions
          
          # Clone the required roles
          git clone https://github.com/Grokon/ansible-role-adduser.git ansible-role-adduser
          git clone https://github.com/bytepark/ansible-cronjob.git ansible-cronjob

          pwd
          ls -l
          echo "running hostname.sh file"
          chmod +x hostname.sh
          ./hostname.sh
